# Generated by Django 4.0.1 on 2022-01-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugar',
            old_name='user_id',
            new_name='user',
        ),
    ]
