# Generated by Django 4.0.1 on 2022-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_user_id_sugar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugar',
            name='dt',
            field=models.DateTimeField(),
        ),
    ]
